### PR TITLE
Fix the install-lal-and-deps.sh script.

### LINKED ISSUE #294: Installation script: compilation failed
I tried to use the installation script `install-lal-and-deps.sh` on Ubuntu 18.04.2 LTS from the current master branch (547daabd5f8392a8dbe93c287f1d79e2dccbddbe).

This results into a compilation error:

```
gprbuild -p -m --target=x86_64-linux  -j0 -XGNATCOLL_MMAP=yes -XGNATCOLL_MADVISE=yes -XGNATCOLL_VERSION=0.0 -XGNATCOLL_OS=unix -XBUILD=PROD  -XLIBRARY_TYPE=static -XXMLADA_BUILD=static -XGPR_BUILD=static \
	-XGNATCOLL_MMAP=yes -XGNATCOLL_MADVISE=yes -XGNATCOLL_VERSION=0.0 -XGNATCOLL_OS=unix -XBUILD=PROD gnatcoll.gpr
Setup
   [mkdir]        object directory for project GnatColl
   [mkdir]        library directory for project GnatColl
Compile
   [C]            update_path.c
   [C]            link_max.c
   [C]            getRSS.c
   [C]            set_std_prefix.c
   [C]            separate_run_path_option.c
   [C]            run_path_option.c
   [C]            gnatcoll_support.c
   [C]            terminals.c
   [C]            objlist_file.c
   [C]            executable_path.c
   [Ada]          gnatcoll-paragraph_filling-words.adb
   [Ada]          gnatcoll-paragraph_filling-badnesses.adb
   [Ada]          gnatcoll-paragraph_filling.adb
   [Ada]          gnatcoll-locks.adb
   [Ada]          gnatcoll-refcount.adb
   [Ada]          gnatcoll-config.adb
gnatcoll-refcount.ads:90:04: warning: in instantiation at gnatcoll-storage_pools-headers.adb:57
gnatcoll-refcount.ads:90:04: warning: possible aliasing problem for type "Header_Access"
gnatcoll-refcount.ads:90:04: warning: use -fno-strict-aliasing switch for references
gnatcoll-refcount.ads:90:04: warning: or use "pragma No_Strict_Aliasing (Header_Access);"
   [Ada]          gnatcoll-pools.adb
   [Ada]          gnatcoll-geometry.adb
   [Ada]          gnatcoll-promises.adb
   [Ada]          gnatcoll-opt_parse.adb
   [Ada]          gnatcoll-templates.adb
   [Ada]          gnatcoll-email-mailboxes.adb
   [Ada]          gnatcoll-utils.adb
gnatcoll-config.ads:63:01: warning: pragma "ADA_05" ignored
   [Ada]          gnatcoll-any_types.adb
   [Ada]          gnatcoll-email-utils.adb
   [Ada]          gnatcoll-remote-db.adb
   [Ada]          gnatcoll-coders-base64.adb
   [Ada]          gnatcoll-os.ads
   [Ada]          gnatcoll-scripts-utils.adb
   [Ada]          gnatcoll-json-utility.adb
   [Ada]          gnatcoll-strings.ads
   [Ada]          gnatcoll-projects-normalize.adb
gnatcoll-email-mailboxes.ads:26:01: warning: pragma "ADA_05" ignored
   [Ada]          gnatcoll-email.adb
gnatcoll-projects-normalize.adb:34:06: warning: license of withed unit "GPR" may be inconsistent
gnatcoll-projects-normalize.adb:35:09: warning: license of withed unit "GPR.Output" may be inconsistent
gnatcoll-projects-normalize.adb:36:09: warning: license of withed unit "GPR.Com" may be inconsistent
gnatcoll-projects-normalize.adb:37:09: warning: license of withed unit "GPR.Tree" may be inconsistent
gnatcoll-projects-normalize.adb:38:09: warning: license of withed unit "GPR.Snames" may be inconsistent
gnatcoll-projects-normalize.adb:39:09: warning: license of withed unit "GPR.Names" may be inconsistent
gnatcoll-projects.adb:11219:41: "Get_Fallback_List" not declared in "Knowledge"
gnatcoll-projects.adb:11224:20: "Free_Knowledge_Base" not declared in "Knowledge"

   compilation of gnatcoll-projects-normalize.adb failed

gprbuild: *** compilation phase failed
Makefile:128: recipe for target 'build-static' failed
make: *** [build-static] Error 4

```

### PR DESCRIPTION
**Pull request by raph-amiard**
Use the travis scripts, in order to more easily stay up to date with
build changes.

closes #294

### CODE REVIEW

File: install-lal-and-deps.sh [hunk 1]
```diff
@@ -22,95 +16,28 @@ INSTALL_DIR=/path/to/install
...
-    python2 setup.py build -j0 --prefix="$INSTALL_DIR"
-    python2 setup.py install --prefix="$INSTALL_DIR"
-)
-(
-    cd gnatcoll-bindings/gmp
-    python2 setup.py build -j0 --prefix="$INSTALL_DIR"
-    python2 setup.py install --prefix="$INSTALL_DIR"
-)
+# You also need to have a GNAT compiler available. Here, for the example we
+# automatically install GNAT Community 2018 for Linux x86_64 (from
```
Comment (ProudPenguin) [inline install-lal-and-deps.sh]: GNAT Community 2019 is installed.

Comment (raph-amiard) [reply install-lal-and-deps.sh]: Good catch ! Thanks :)
